// Re-export stricli-utils for convenience

// Re-export codegen for convenience
export {
  type CliPackageInfo,
  createRouteWatcher,
  fileToRouteName,
  findCliPackages,
  findEmptyFiles,
  type GeneratedRouteMap,
  type GeneratorOptions,
  generateHandlerTemplate,
  generateLazyRouteTemplate,
  generateRepoRouteMaps,
  generateRootTemplate,
  generateRouteGroupTemplate,
  generateRouteMap,
  generateRouteTemplate,
  getDefaultConfig,
  hasRootConfig,
  hasRouteConfig,
  isCommandFile,
  isEmptyFile,
  isHandlerFile,
  isLazyFile,
  isLazyRoute,
  isSpecialFile,
  pathToIdentifier,
  populateStubFile,
  type RouteFileExports,
  type RouteGroupConfig,
  type RouteWatcher,
  readConfig,
  routeToImportName,
  type ScannedRoute,
  SPECIAL_FILES,
  type StricliKitConfig,
  type StubResult,
  scanCommandsDirectory,
  type TemplateOptions,
  type WatcherOptions,
} from "@macalinao/stricli-codegen";
export {
  type AppConfig,
  type AppDynamicContext,
  type CommandContextType,
  type CommandDocs,
  type CommandHandler,
  type CommandParams,
  choiceParser,
  createAppContext,
  createOutput,
  defineAppConfig,
  defineHandler,
  defineParameters,
  defineRoute,
  defineRouteGroup,
  type ExtendedContext,
  type ExtractArgs,
  type ExtractFlags,
  type ExtractFlagType,
  extendContext,
  globParser,
  jsonParser,
  type OutputHelpers,
  type PathParserOptions,
  pathParser,
  type Route,
  type RouteGroupDocs,
  type RouteGroupMeta,
} from "@macalinao/stricli-utils";
// Export the CLI app for programmatic use
export { app } from "./app.js";
